### PR TITLE
Syncing the NFT smart contract data in redis

### PR DESCRIPTION
**Pull request by hamzatrq**
Closing the previous PR and opening this one. In previous code we were storing metadata links and tokenIDs in redis. Which had some bugs. While storing the data the strings were breaking into character objects. Also the previous implementation was crashing for some values of metadata uri which was covered by adding checks for ipfs. Furthermore the function for syncing the data was only called once when starting the server which was not the desired behavior. Storing only metadata uri was creating issues on backend-api where a lot of requests to third-party storage services were being made for every user request.

In order to correct all of these issues I decided to convert the functions into two cron jobs and to store complete metadata in redis instead of just links. This way the system can work and scale easily. 

There was a choice to either choose the current syncing code. Where there is a function that gets called at startup and retrieves and stores data from all previous events and then another functions that listens for all new events from smart contract and stores data for those events. But with that implementation we will also have to take care of block reorganization and block rejection. So I decided to go with the cron job.

There are two cron jobs.

1. syncMetadata: It gets all "URI" events which gets called whenever the URI of a token changes (also gets called when the token is minted) and then sends request for fetching the metadata through node-fetch and if JSON is received stores it into redis.
2. syncTokenIDOwners: It gets all the Transfer events and from there creates a list of all the owners and their tokenIDs and stores them in redis.

### CODE REVIEW

**Comment by avaer** [comment]
What is the maximum level of lag/desync with these cron jobs?
How long must the user wait (avg and max) on e.g. a transfer or update of the token metadatas?

**Comment by avaer** [comment]
Ideally I do think we should be using an ethereum network websocket events listener (infura).

**Comment by avaer** [comment]
I'm fine with this for now though, it's better than nothing. I just don't know if it will be perceived as performant enough to ship with.

**Review by avaer — APPROVED** [review]

**Comment by hamzatrq** [comment]
> What is the maximum level of lag/desync with these cron jobs? How long must the user wait (avg and max) on e.g. a transfer or update of the token metadatas?

The cron jobs are fast and runs every minute. Which means that the user will not have to wait for more than a minute. Also the scenario for the newly minted tokens can be handled by the frontend. By waiting for the transaction to process and if the promise is successful just show the NFT.



> Ideally I do think we should be using an ethereum network websocket events listener (infura).
True. But these cronjobs are also performant enough to be shiped for now. I have used jobs for event with more than 100k active user apps and they work satisfactory. But yes in future we can change it.

**Pull request merged**
